#Gradle
org.gradle.jvmargs=-Xmx64g -XX:MaxMetaspaceSize=8g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.workers.max=2

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx32g -XX:+UseG1GC

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#Project
mavenGroupId=dev.ohs.fhir
mavenArtifactId=fhir-path
mavenVersion=1.0.0-beta05
androidNamespace=dev.ohs.fhir.fhirpath

#Kotest
io.kotest.multiplatform.compiler.plugin.enabled=false
kotest.compiler.plugin.enabled=false
kotlin.incremental.js=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
