/*
 * Copyright 2026 Open Health Stack Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.ohs.fhir.model.r4b.ext

import dev.ohs.fhir.model.r4b.Account
import dev.ohs.fhir.model.r4b.ActivityDefinition
import dev.ohs.fhir.model.r4b.AdministrableProductDefinition
import dev.ohs.fhir.model.r4b.AdverseEvent
import dev.ohs.fhir.model.r4b.AllergyIntolerance
import dev.ohs.fhir.model.r4b.Appointment
import dev.ohs.fhir.model.r4b.AuditEvent
import dev.ohs.fhir.model.r4b.BackboneElement
import dev.ohs.fhir.model.r4b.BiologicallyDerivedProduct
import dev.ohs.fhir.model.r4b.Bundle
import dev.ohs.fhir.model.r4b.CapabilityStatement
import dev.ohs.fhir.model.r4b.CarePlan
import dev.ohs.fhir.model.r4b.CareTeam
import dev.ohs.fhir.model.r4b.CatalogEntry
import dev.ohs.fhir.model.r4b.ChargeItem
import dev.ohs.fhir.model.r4b.ChargeItemDefinition
import dev.ohs.fhir.model.r4b.Citation
import dev.ohs.fhir.model.r4b.Claim
import dev.ohs.fhir.model.r4b.ClaimResponse
import dev.ohs.fhir.model.r4b.ClinicalImpression
import dev.ohs.fhir.model.r4b.ClinicalUseDefinition
import dev.ohs.fhir.model.r4b.CodeSystem
import dev.ohs.fhir.model.r4b.Communication
import dev.ohs.fhir.model.r4b.CommunicationRequest
import dev.ohs.fhir.model.r4b.CompartmentDefinition
import dev.ohs.fhir.model.r4b.Composition
import dev.ohs.fhir.model.r4b.ConceptMap
import dev.ohs.fhir.model.r4b.Condition
import dev.ohs.fhir.model.r4b.Consent
import dev.ohs.fhir.model.r4b.Contract
import dev.ohs.fhir.model.r4b.Coverage
import dev.ohs.fhir.model.r4b.CoverageEligibilityRequest
import dev.ohs.fhir.model.r4b.CoverageEligibilityResponse
import dev.ohs.fhir.model.r4b.DetectedIssue
import dev.ohs.fhir.model.r4b.Device
import dev.ohs.fhir.model.r4b.DeviceDefinition
import dev.ohs.fhir.model.r4b.DeviceMetric
import dev.ohs.fhir.model.r4b.DeviceRequest
import dev.ohs.fhir.model.r4b.DiagnosticReport
import dev.ohs.fhir.model.r4b.DocumentManifest
import dev.ohs.fhir.model.r4b.DocumentReference
import dev.ohs.fhir.model.r4b.Encounter
import dev.ohs.fhir.model.r4b.EpisodeOfCare
import dev.ohs.fhir.model.r4b.Evidence
import dev.ohs.fhir.model.r4b.EvidenceReport
import dev.ohs.fhir.model.r4b.EvidenceVariable
import dev.ohs.fhir.model.r4b.ExampleScenario
import dev.ohs.fhir.model.r4b.ExplanationOfBenefit
import dev.ohs.fhir.model.r4b.FamilyMemberHistory
import dev.ohs.fhir.model.r4b.Goal
import dev.ohs.fhir.model.r4b.GraphDefinition
import dev.ohs.fhir.model.r4b.Group
import dev.ohs.fhir.model.r4b.HealthcareService
import dev.ohs.fhir.model.r4b.ImagingStudy
import dev.ohs.fhir.model.r4b.Immunization
import dev.ohs.fhir.model.r4b.ImmunizationRecommendation
import dev.ohs.fhir.model.r4b.ImplementationGuide
import dev.ohs.fhir.model.r4b.Ingredient
import dev.ohs.fhir.model.r4b.InsurancePlan
import dev.ohs.fhir.model.r4b.Invoice
import dev.ohs.fhir.model.r4b.Linkage
import dev.ohs.fhir.model.r4b.List as R4bList
import dev.ohs.fhir.model.r4b.Location
import dev.ohs.fhir.model.r4b.ManufacturedItemDefinition
import dev.ohs.fhir.model.r4b.Measure
import dev.ohs.fhir.model.r4b.MeasureReport
import dev.ohs.fhir.model.r4b.Medication
import dev.ohs.fhir.model.r4b.MedicationAdministration
import dev.ohs.fhir.model.r4b.MedicationDispense
import dev.ohs.fhir.model.r4b.MedicationKnowledge
import dev.ohs.fhir.model.r4b.MedicationRequest
import dev.ohs.fhir.model.r4b.MedicinalProductDefinition
import dev.ohs.fhir.model.r4b.MessageDefinition
import dev.ohs.fhir.model.r4b.MessageHeader
import dev.ohs.fhir.model.r4b.MolecularSequence
import dev.ohs.fhir.model.r4b.NamingSystem
import dev.ohs.fhir.model.r4b.NutritionOrder
import dev.ohs.fhir.model.r4b.NutritionProduct
import dev.ohs.fhir.model.r4b.Observation
import dev.ohs.fhir.model.r4b.ObservationDefinition
import dev.ohs.fhir.model.r4b.OperationDefinition
import dev.ohs.fhir.model.r4b.OperationOutcome
import dev.ohs.fhir.model.r4b.Organization
import dev.ohs.fhir.model.r4b.PackagedProductDefinition
import dev.ohs.fhir.model.r4b.Parameters
import dev.ohs.fhir.model.r4b.Patient
import dev.ohs.fhir.model.r4b.PaymentReconciliation
import dev.ohs.fhir.model.r4b.Person
import dev.ohs.fhir.model.r4b.PlanDefinition
import dev.ohs.fhir.model.r4b.Practitioner
import dev.ohs.fhir.model.r4b.PractitionerRole
import dev.ohs.fhir.model.r4b.Procedure
import dev.ohs.fhir.model.r4b.Provenance
import dev.ohs.fhir.model.r4b.Questionnaire
import dev.ohs.fhir.model.r4b.QuestionnaireResponse
import dev.ohs.fhir.model.r4b.RegulatedAuthorization
import dev.ohs.fhir.model.r4b.RelatedPerson
import dev.ohs.fhir.model.r4b.RequestGroup
import dev.ohs.fhir.model.r4b.ResearchElementDefinition
import dev.ohs.fhir.model.r4b.ResearchStudy
import dev.ohs.fhir.model.r4b.RiskAssessment
import dev.ohs.fhir.model.r4b.SearchParameter
import dev.ohs.fhir.model.r4b.Specimen
import dev.ohs.fhir.model.r4b.SpecimenDefinition
import dev.ohs.fhir.model.r4b.StructureDefinition
import dev.ohs.fhir.model.r4b.StructureMap
import dev.ohs.fhir.model.r4b.Subscription
import dev.ohs.fhir.model.r4b.SubscriptionStatus
import dev.ohs.fhir.model.r4b.SubscriptionTopic
import dev.ohs.fhir.model.r4b.Substance
import dev.ohs.fhir.model.r4b.SubstanceDefinition
import dev.ohs.fhir.model.r4b.SupplyDelivery
import dev.ohs.fhir.model.r4b.SupplyRequest
import dev.ohs.fhir.model.r4b.Task
import dev.ohs.fhir.model.r4b.TerminologyCapabilities
import dev.ohs.fhir.model.r4b.TestReport
import dev.ohs.fhir.model.r4b.TestScript
import dev.ohs.fhir.model.r4b.ValueSet
import dev.ohs.fhir.model.r4b.VerificationResult
import dev.ohs.fhir.model.r4b.VisionPrescription
import kotlin.Any
import kotlin.Boolean
import kotlin.String
import kotlin.collections.List as CollectionsList

private fun BackboneElement.getProperty0(name: String): Any? =
  when (this) {
    is SubscriptionTopic.ResourceTrigger -> getProperty(name)
    is SubscriptionTopic.ResourceTrigger.QueryCriteria -> getProperty(name)
    is SubscriptionTopic.EventTrigger -> getProperty(name)
    is SubscriptionTopic.CanFilterBy -> getProperty(name)
    is SubscriptionTopic.NotificationShape -> getProperty(name)
    is ExampleScenario.Actor -> getProperty(name)
    is ExampleScenario.Instance -> getProperty(name)
    is ExampleScenario.Instance.Version -> getProperty(name)
    is ExampleScenario.Instance.ContainedInstance -> getProperty(name)
    is ExampleScenario.Process -> getProperty(name)
    is ExampleScenario.Process.Step -> getProperty(name)
    is ExampleScenario.Process.Step.Operation -> getProperty(name)
    is ExampleScenario.Process.Step.Alternative -> getProperty(name)
    is Appointment.Participant -> getProperty(name)
    is Condition.Stage -> getProperty(name)
    is Condition.Evidence -> getProperty(name)
    is R4bList.Entry -> getProperty(name)
    is ChargeItem.Performer -> getProperty(name)
    is VerificationResult.PrimarySource -> getProperty(name)
    is VerificationResult.Attestation -> getProperty(name)
    is VerificationResult.Validator -> getProperty(name)
    is SupplyDelivery.SuppliedItem -> getProperty(name)
    is Composition.Attester -> getProperty(name)
    is Composition.RelatesTo -> getProperty(name)
    is Composition.Event -> getProperty(name)
    is Composition.Section -> getProperty(name)
    is Encounter.StatusHistory -> getProperty(name)
    is Encounter.ClassHistory -> getProperty(name)
    is Encounter.Participant -> getProperty(name)
    is Encounter.Diagnosis -> getProperty(name)
    is Encounter.Hospitalization -> getProperty(name)
    is Encounter.Location -> getProperty(name)
    is MedicationAdministration.Performer -> getProperty(name)
    is MedicationAdministration.Dosage -> getProperty(name)
    is DocumentManifest.Related -> getProperty(name)
    is Claim.Related -> getProperty(name)
    is Claim.Payee -> getProperty(name)
    is Claim.CareTeam -> getProperty(name)
    is Claim.SupportingInfo -> getProperty(name)
    is Claim.Diagnosis -> getProperty(name)
    is Claim.Procedure -> getProperty(name)
    is Claim.Insurance -> getProperty(name)
    is Claim.Accident -> getProperty(name)
    is Claim.Item -> getProperty(name)
    is Claim.Item.Detail -> getProperty(name)
    is Claim.Item.Detail.SubDetail -> getProperty(name)
    is DeviceMetric.Calibration -> getProperty(name)
    is AuditEvent.Agent -> getProperty(name)
    is AuditEvent.Agent.Network -> getProperty(name)
    is AuditEvent.Source -> getProperty(name)
    is AuditEvent.Entity -> getProperty(name)
    is AuditEvent.Entity.Detail -> getProperty(name)
    is CarePlan.Activity -> getProperty(name)
    is CarePlan.Activity.Detail -> getProperty(name)
    is Linkage.Item -> getProperty(name)
    is CoverageEligibilityResponse.Insurance -> getProperty(name)
    is CoverageEligibilityResponse.Insurance.Item -> getProperty(name)
    is CoverageEligibilityResponse.Insurance.Item.Benefit -> getProperty(name)
    is CoverageEligibilityResponse.Error -> getProperty(name)
    is QuestionnaireResponse.Item -> getProperty(name)
    is QuestionnaireResponse.Item.Answer -> getProperty(name)
    is Location.Position -> getProperty(name)
    is Location.HoursOfOperation -> getProperty(name)
    is InsurancePlan.Contact -> getProperty(name)
    is InsurancePlan.Coverage -> getProperty(name)
    is InsurancePlan.Coverage.Benefit -> getProperty(name)
    is InsurancePlan.Coverage.Benefit.Limit -> getProperty(name)
    is InsurancePlan.Plan -> getProperty(name)
    is InsurancePlan.Plan.GeneralCost -> getProperty(name)
    is InsurancePlan.Plan.SpecificCost -> getProperty(name)
    is InsurancePlan.Plan.SpecificCost.Benefit -> getProperty(name)
    is InsurancePlan.Plan.SpecificCost.Benefit.Cost -> getProperty(name)
    is Citation.Summary -> getProperty(name)
    is Citation.Classification -> getProperty(name)
    is Citation.StatusDate -> getProperty(name)
    is Citation.RelatesTo -> getProperty(name)
    is Citation.CitedArtifact -> getProperty(name)
    is Citation.CitedArtifact.Version -> getProperty(name)
    is Citation.CitedArtifact.StatusDate -> getProperty(name)
    is Citation.CitedArtifact.Title -> getProperty(name)
    is Citation.CitedArtifact.Abstract -> getProperty(name)
    is Citation.CitedArtifact.Part -> getProperty(name)
    is Citation.CitedArtifact.RelatesTo -> getProperty(name)
    is Citation.CitedArtifact.PublicationForm -> getProperty(name)
    is Citation.CitedArtifact.PublicationForm.PublishedIn -> getProperty(name)
    is Citation.CitedArtifact.PublicationForm.PeriodicRelease -> getProperty(name)
    is Citation.CitedArtifact.PublicationForm.PeriodicRelease.DateOfPublication -> getProperty(name)
    is Citation.CitedArtifact.WebLocation -> getProperty(name)
    is Citation.CitedArtifact.Classification -> getProperty(name)
    is Citation.CitedArtifact.Classification.WhoClassified -> getProperty(name)
    is Citation.CitedArtifact.Contributorship -> getProperty(name)
    is Citation.CitedArtifact.Contributorship.Entry -> getProperty(name)
    is Citation.CitedArtifact.Contributorship.Entry.AffiliationInfo -> getProperty(name)
    is Citation.CitedArtifact.Contributorship.Entry.ContributionInstance -> getProperty(name)
    is Citation.CitedArtifact.Contributorship.Summary -> getProperty(name)
    is SubscriptionStatus.NotificationEvent -> getProperty(name)
    is Measure.Group -> getProperty(name)
    is Measure.Group.Population -> getProperty(name)
    is Measure.Group.Stratifier -> getProperty(name)
    is Measure.Group.Stratifier.Component -> getProperty(name)
    is Measure.SupplementalData -> getProperty(name)
    is ActivityDefinition.Participant -> getProperty(name)
    is ActivityDefinition.DynamicValue -> getProperty(name)
    is EpisodeOfCare.StatusHistory -> getProperty(name)
    is EpisodeOfCare.Diagnosis -> getProperty(name)
    is DeviceRequest.Parameter -> getProperty(name)
    is CapabilityStatement.Software -> getProperty(name)
    is CapabilityStatement.Implementation -> getProperty(name)
    is CapabilityStatement.Rest -> getProperty(name)
    is CapabilityStatement.Rest.Security -> getProperty(name)
    is CapabilityStatement.Rest.Resource -> getProperty(name)
    is CapabilityStatement.Rest.Resource.Interaction -> getProperty(name)
    is CapabilityStatement.Rest.Resource.SearchParam -> getProperty(name)
    is CapabilityStatement.Rest.Resource.Operation -> getProperty(name)
    is CapabilityStatement.Rest.Interaction -> getProperty(name)
    is CapabilityStatement.Messaging -> getProperty(name)
    is CapabilityStatement.Messaging.Endpoint -> getProperty(name)
    is CapabilityStatement.Messaging.SupportedMessage -> getProperty(name)
    is CapabilityStatement.Document -> getProperty(name)
    is Substance.Instance -> getProperty(name)
    is Substance.Ingredient -> getProperty(name)
    is CatalogEntry.RelatedEntry -> getProperty(name)
    is Group.Characteristic -> getProperty(name)
    is Group.Member -> getProperty(name)
    is ImagingStudy.Series -> getProperty(name)
    is ImagingStudy.Series.Performer -> getProperty(name)
    is ImagingStudy.Series.Instance -> getProperty(name)
    is Organization.Contact -> getProperty(name)
    is MolecularSequence.ReferenceSeq -> getProperty(name)
    is MolecularSequence.Variant -> getProperty(name)
    is MolecularSequence.Quality -> getProperty(name)
    is MolecularSequence.Quality.Roc -> getProperty(name)
    is MolecularSequence.Repository -> getProperty(name)
    is MolecularSequence.StructureVariant -> getProperty(name)
    is MolecularSequence.StructureVariant.Outer -> getProperty(name)
    is MolecularSequence.StructureVariant.Inner -> getProperty(name)
    is RegulatedAuthorization.Case -> getProperty(name)
    is ChargeItemDefinition.Applicability -> getProperty(name)
    is ChargeItemDefinition.PropertyGroup -> getProperty(name)
    is ChargeItemDefinition.PropertyGroup.PriceComponent -> getProperty(name)
    is Questionnaire.Item -> getProperty(name)
    is Questionnaire.Item.EnableWhen -> getProperty(name)
    is Questionnaire.Item.AnswerOption -> getProperty(name)
    is Questionnaire.Item.Initial -> getProperty(name)
    is TestScript.Origin -> getProperty(name)
    is TestScript.Destination -> getProperty(name)
    is TestScript.Metadata -> getProperty(name)
    is TestScript.Metadata.Link -> getProperty(name)
    is TestScript.Metadata.Capability -> getProperty(name)
    is TestScript.Fixture -> getProperty(name)
    else -> null
  }

private fun BackboneElement.getProperty1(name: String): Any? =
  when (this) {
    is TestScript.Variable -> getProperty(name)
    is TestScript.Setup -> getProperty(name)
    is TestScript.Setup.Action -> getProperty(name)
    is TestScript.Setup.Action.Operation -> getProperty(name)
    is TestScript.Setup.Action.Operation.RequestHeader -> getProperty(name)
    is TestScript.Setup.Action.Assert -> getProperty(name)
    is TestScript.Test -> getProperty(name)
    is TestScript.Test.Action -> getProperty(name)
    is TestScript.Teardown -> getProperty(name)
    is TestScript.Teardown.Action -> getProperty(name)
    is ResearchStudy.Arm -> getProperty(name)
    is ResearchStudy.Objective -> getProperty(name)
    is PractitionerRole.AvailableTime -> getProperty(name)
    is PractitionerRole.NotAvailable -> getProperty(name)
    is TestReport.Participant -> getProperty(name)
    is TestReport.Setup -> getProperty(name)
    is TestReport.Setup.Action -> getProperty(name)
    is TestReport.Setup.Action.Operation -> getProperty(name)
    is TestReport.Setup.Action.Assert -> getProperty(name)
    is TestReport.Test -> getProperty(name)
    is TestReport.Test.Action -> getProperty(name)
    is TestReport.Teardown -> getProperty(name)
    is TestReport.Teardown.Action -> getProperty(name)
    is MeasureReport.Group -> getProperty(name)
    is MeasureReport.Group.Population -> getProperty(name)
    is MeasureReport.Group.Stratifier -> getProperty(name)
    is MeasureReport.Group.Stratifier.Stratum -> getProperty(name)
    is MeasureReport.Group.Stratifier.Stratum.Component -> getProperty(name)
    is MeasureReport.Group.Stratifier.Stratum.Population -> getProperty(name)
    is SubstanceDefinition.Moiety -> getProperty(name)
    is SubstanceDefinition.Property -> getProperty(name)
    is SubstanceDefinition.MolecularWeight -> getProperty(name)
    is SubstanceDefinition.Structure -> getProperty(name)
    is SubstanceDefinition.Structure.Representation -> getProperty(name)
    is SubstanceDefinition.Code -> getProperty(name)
    is SubstanceDefinition.Name -> getProperty(name)
    is SubstanceDefinition.Name.Official -> getProperty(name)
    is SubstanceDefinition.Relationship -> getProperty(name)
    is SubstanceDefinition.SourceMaterial -> getProperty(name)
    is SupplyRequest.Parameter -> getProperty(name)
    is Provenance.Agent -> getProperty(name)
    is Provenance.Entity -> getProperty(name)
    is RiskAssessment.Prediction -> getProperty(name)
    is Parameters.Parameter -> getProperty(name)
    is HealthcareService.Eligibility -> getProperty(name)
    is HealthcareService.AvailableTime -> getProperty(name)
    is HealthcareService.NotAvailable -> getProperty(name)
    is RelatedPerson.Communication -> getProperty(name)
    is Evidence.VariableDefinition -> getProperty(name)
    is Evidence.Statistic -> getProperty(name)
    is Evidence.Statistic.SampleSize -> getProperty(name)
    is Evidence.Statistic.AttributeEstimate -> getProperty(name)
    is Evidence.Statistic.ModelCharacteristic -> getProperty(name)
    is Evidence.Statistic.ModelCharacteristic.Variable -> getProperty(name)
    is Evidence.Certainty -> getProperty(name)
    is NamingSystem.UniqueId -> getProperty(name)
    is VisionPrescription.LensSpecification -> getProperty(name)
    is VisionPrescription.LensSpecification.Prism -> getProperty(name)
    is ExplanationOfBenefit.Related -> getProperty(name)
    is ExplanationOfBenefit.Payee -> getProperty(name)
    is ExplanationOfBenefit.CareTeam -> getProperty(name)
    is ExplanationOfBenefit.SupportingInfo -> getProperty(name)
    is ExplanationOfBenefit.Diagnosis -> getProperty(name)
    is ExplanationOfBenefit.Procedure -> getProperty(name)
    is ExplanationOfBenefit.Insurance -> getProperty(name)
    is ExplanationOfBenefit.Accident -> getProperty(name)
    is ExplanationOfBenefit.Item -> getProperty(name)
    is ExplanationOfBenefit.Item.Adjudication -> getProperty(name)
    is ExplanationOfBenefit.Item.Detail -> getProperty(name)
    is ExplanationOfBenefit.Item.Detail.SubDetail -> getProperty(name)
    is ExplanationOfBenefit.AddItem -> getProperty(name)
    is ExplanationOfBenefit.AddItem.Detail -> getProperty(name)
    is ExplanationOfBenefit.AddItem.Detail.SubDetail -> getProperty(name)
    is ExplanationOfBenefit.Total -> getProperty(name)
    is ExplanationOfBenefit.Payment -> getProperty(name)
    is ExplanationOfBenefit.ProcessNote -> getProperty(name)
    is ExplanationOfBenefit.BenefitBalance -> getProperty(name)
    is ExplanationOfBenefit.BenefitBalance.Financial -> getProperty(name)
    is PackagedProductDefinition.LegalStatusOfSupply -> getProperty(name)
    is PackagedProductDefinition.Package -> getProperty(name)
    is PackagedProductDefinition.Package.ShelfLifeStorage -> getProperty(name)
    is PackagedProductDefinition.Package.Property -> getProperty(name)
    is PackagedProductDefinition.Package.ContainedItem -> getProperty(name)
    is Patient.Contact -> getProperty(name)
    is Patient.Communication -> getProperty(name)
    is Patient.Link -> getProperty(name)
    is ManufacturedItemDefinition.Property -> getProperty(name)
    is Specimen.Collection -> getProperty(name)
    is Specimen.Processing -> getProperty(name)
    is Specimen.Container -> getProperty(name)
    is FamilyMemberHistory.Condition -> getProperty(name)
    is ResearchElementDefinition.Characteristic -> getProperty(name)
    is OperationDefinition.Parameter -> getProperty(name)
    is OperationDefinition.Parameter.Binding -> getProperty(name)
    is OperationDefinition.Parameter.ReferencedFrom -> getProperty(name)
    is OperationDefinition.Overload -> getProperty(name)
    is GraphDefinition.Link -> getProperty(name)
    is GraphDefinition.Link.Target -> getProperty(name)
    is GraphDefinition.Link.Target.Compartment -> getProperty(name)
    is Medication.Ingredient -> getProperty(name)
    is Medication.Batch -> getProperty(name)
    is DiagnosticReport.Media -> getProperty(name)
    is RequestGroup.Action -> getProperty(name)
    is RequestGroup.Action.Condition -> getProperty(name)
    is RequestGroup.Action.RelatedAction -> getProperty(name)
    is MessageHeader.Destination -> getProperty(name)
    is MessageHeader.Source -> getProperty(name)
    is MessageHeader.Response -> getProperty(name)
    is DeviceDefinition.UdiDeviceIdentifier -> getProperty(name)
    is DeviceDefinition.DeviceName -> getProperty(name)
    is DeviceDefinition.Specialization -> getProperty(name)
    is DeviceDefinition.Capability -> getProperty(name)
    is DeviceDefinition.Property -> getProperty(name)
    is DeviceDefinition.Material -> getProperty(name)
    is Goal.Target -> getProperty(name)
    is ObservationDefinition.QuantitativeDetails -> getProperty(name)
    is ObservationDefinition.QualifiedInterval -> getProperty(name)
    is Immunization.Performer -> getProperty(name)
    is Immunization.Education -> getProperty(name)
    is Immunization.Reaction -> getProperty(name)
    is Immunization.ProtocolApplied -> getProperty(name)
    is ValueSet.Compose -> getProperty(name)
    is ValueSet.Compose.Include -> getProperty(name)
    is ValueSet.Compose.Include.Concept -> getProperty(name)
    is ValueSet.Compose.Include.Concept.Designation -> getProperty(name)
    is ValueSet.Compose.Include.Filter -> getProperty(name)
    is ValueSet.Expansion -> getProperty(name)
    is ValueSet.Expansion.Parameter -> getProperty(name)
    is ValueSet.Expansion.Contains -> getProperty(name)
    is ClaimResponse.Item -> getProperty(name)
    is ClaimResponse.Item.Adjudication -> getProperty(name)
    is ClaimResponse.Item.Detail -> getProperty(name)
    is ClaimResponse.Item.Detail.SubDetail -> getProperty(name)
    is ClaimResponse.AddItem -> getProperty(name)
    is ClaimResponse.AddItem.Detail -> getProperty(name)
    is ClaimResponse.AddItem.Detail.SubDetail -> getProperty(name)
    is ClaimResponse.Total -> getProperty(name)
    is ClaimResponse.Payment -> getProperty(name)
    is ClaimResponse.ProcessNote -> getProperty(name)
    is ClaimResponse.Insurance -> getProperty(name)
    is ClaimResponse.Error -> getProperty(name)
    is Contract.ContentDefinition -> getProperty(name)
    is Contract.Term -> getProperty(name)
    is Contract.Term.SecurityLabel -> getProperty(name)
    is Contract.Term.Offer -> getProperty(name)
    is Contract.Term.Offer.Party -> getProperty(name)
    is Contract.Term.Offer.Answer -> getProperty(name)
    is Contract.Term.Asset -> getProperty(name)
    is Contract.Term.Asset.Context -> getProperty(name)
    is Contract.Term.Asset.ValuedItem -> getProperty(name)
    else -> null
  }

private fun BackboneElement.getProperty2(name: String): Any? =
  when (this) {
    is Contract.Term.Action -> getProperty(name)
    is Contract.Term.Action.Subject -> getProperty(name)
    is Contract.Signer -> getProperty(name)
    is Contract.Friendly -> getProperty(name)
    is Contract.Legal -> getProperty(name)
    is Contract.Rule -> getProperty(name)
    is BiologicallyDerivedProduct.Collection -> getProperty(name)
    is BiologicallyDerivedProduct.Processing -> getProperty(name)
    is BiologicallyDerivedProduct.Manipulation -> getProperty(name)
    is BiologicallyDerivedProduct.Storage -> getProperty(name)
    is TerminologyCapabilities.Software -> getProperty(name)
    is TerminologyCapabilities.Implementation -> getProperty(name)
    is TerminologyCapabilities.CodeSystem -> getProperty(name)
    is TerminologyCapabilities.CodeSystem.Version -> getProperty(name)
    is TerminologyCapabilities.CodeSystem.Version.Filter -> getProperty(name)
    is TerminologyCapabilities.Expansion -> getProperty(name)
    is TerminologyCapabilities.Expansion.Parameter -> getProperty(name)
    is TerminologyCapabilities.ValidateCode -> getProperty(name)
    is TerminologyCapabilities.Translation -> getProperty(name)
    is TerminologyCapabilities.Closure -> getProperty(name)
    is ClinicalUseDefinition.Contraindication -> getProperty(name)
    is ClinicalUseDefinition.Contraindication.OtherTherapy -> getProperty(name)
    is ClinicalUseDefinition.Indication -> getProperty(name)
    is ClinicalUseDefinition.Interaction -> getProperty(name)
    is ClinicalUseDefinition.Interaction.Interactant -> getProperty(name)
    is ClinicalUseDefinition.UndesirableEffect -> getProperty(name)
    is ClinicalUseDefinition.Warning -> getProperty(name)
    is SpecimenDefinition.TypeTested -> getProperty(name)
    is SpecimenDefinition.TypeTested.Container -> getProperty(name)
    is SpecimenDefinition.TypeTested.Container.Additive -> getProperty(name)
    is SpecimenDefinition.TypeTested.Handling -> getProperty(name)
    is ConceptMap.Group -> getProperty(name)
    is ConceptMap.Group.Element -> getProperty(name)
    is ConceptMap.Group.Element.Target -> getProperty(name)
    is ConceptMap.Group.Element.Target.DependsOn -> getProperty(name)
    is ConceptMap.Group.Unmapped -> getProperty(name)
    is Invoice.Participant -> getProperty(name)
    is Invoice.LineItem -> getProperty(name)
    is Invoice.LineItem.PriceComponent -> getProperty(name)
    is StructureDefinition.Mapping -> getProperty(name)
    is StructureDefinition.Context -> getProperty(name)
    is StructureDefinition.Snapshot -> getProperty(name)
    is StructureDefinition.Differential -> getProperty(name)
    is CommunicationRequest.Payload -> getProperty(name)
    is DetectedIssue.Evidence -> getProperty(name)
    is DetectedIssue.Mitigation -> getProperty(name)
    is EvidenceVariable.Characteristic -> getProperty(name)
    is EvidenceVariable.Characteristic.TimeFromStart -> getProperty(name)
    is EvidenceVariable.Category -> getProperty(name)
    is Bundle.Link -> getProperty(name)
    is Bundle.Entry -> getProperty(name)
    is Bundle.Entry.Search -> getProperty(name)
    is Bundle.Entry.Request -> getProperty(name)
    is Bundle.Entry.Response -> getProperty(name)
    is MessageDefinition.Focus -> getProperty(name)
    is MessageDefinition.AllowedResponse -> getProperty(name)
    is ImplementationGuide.DependsOn -> getProperty(name)
    is ImplementationGuide.Global -> getProperty(name)
    is ImplementationGuide.Definition -> getProperty(name)
    is ImplementationGuide.Definition.Grouping -> getProperty(name)
    is ImplementationGuide.Definition.Resource -> getProperty(name)
    is ImplementationGuide.Definition.Page -> getProperty(name)
    is ImplementationGuide.Definition.Parameter -> getProperty(name)
    is ImplementationGuide.Definition.Template -> getProperty(name)
    is ImplementationGuide.Manifest -> getProperty(name)
    is ImplementationGuide.Manifest.Resource -> getProperty(name)
    is ImplementationGuide.Manifest.Page -> getProperty(name)
    is NutritionOrder.OralDiet -> getProperty(name)
    is NutritionOrder.OralDiet.Nutrient -> getProperty(name)
    is NutritionOrder.OralDiet.Texture -> getProperty(name)
    is NutritionOrder.Supplement -> getProperty(name)
    is NutritionOrder.EnteralFormula -> getProperty(name)
    is NutritionOrder.EnteralFormula.Administration -> getProperty(name)
    is CoverageEligibilityRequest.SupportingInfo -> getProperty(name)
    is CoverageEligibilityRequest.Insurance -> getProperty(name)
    is CoverageEligibilityRequest.Item -> getProperty(name)
    is CoverageEligibilityRequest.Item.Diagnosis -> getProperty(name)
    is CodeSystem.Filter -> getProperty(name)
    is CodeSystem.Property -> getProperty(name)
    is CodeSystem.Concept -> getProperty(name)
    is CodeSystem.Concept.Designation -> getProperty(name)
    is CodeSystem.Concept.Property -> getProperty(name)
    is MedicationRequest.DispenseRequest -> getProperty(name)
    is MedicationRequest.DispenseRequest.InitialFill -> getProperty(name)
    is MedicationRequest.Substitution -> getProperty(name)
    is ImmunizationRecommendation.Recommendation -> getProperty(name)
    is ImmunizationRecommendation.Recommendation.DateCriterion -> getProperty(name)
    is CompartmentDefinition.Resource -> getProperty(name)
    is Coverage.Class -> getProperty(name)
    is Coverage.CostToBeneficiary -> getProperty(name)
    is Coverage.CostToBeneficiary.Exception -> getProperty(name)
    is PaymentReconciliation.Detail -> getProperty(name)
    is PaymentReconciliation.ProcessNote -> getProperty(name)
    is MedicationKnowledge.RelatedMedicationKnowledge -> getProperty(name)
    is MedicationKnowledge.Monograph -> getProperty(name)
    is MedicationKnowledge.Ingredient -> getProperty(name)
    is MedicationKnowledge.Cost -> getProperty(name)
    is MedicationKnowledge.MonitoringProgram -> getProperty(name)
    is MedicationKnowledge.AdministrationGuidelines -> getProperty(name)
    is MedicationKnowledge.AdministrationGuidelines.Dosage -> getProperty(name)
    is MedicationKnowledge.AdministrationGuidelines.PatientCharacteristics -> getProperty(name)
    is MedicationKnowledge.MedicineClassification -> getProperty(name)
    is MedicationKnowledge.Packaging -> getProperty(name)
    is MedicationKnowledge.DrugCharacteristic -> getProperty(name)
    is MedicationKnowledge.Regulatory -> getProperty(name)
    is MedicationKnowledge.Regulatory.Substitution -> getProperty(name)
    is MedicationKnowledge.Regulatory.Schedule -> getProperty(name)
    is MedicationKnowledge.Regulatory.MaxDispense -> getProperty(name)
    is MedicationKnowledge.Kinetics -> getProperty(name)
    is SearchParameter.Component -> getProperty(name)
    is Person.Link -> getProperty(name)
    is AdministrableProductDefinition.Property -> getProperty(name)
    is AdministrableProductDefinition.RouteOfAdministration -> getProperty(name)
    is AdministrableProductDefinition.RouteOfAdministration.TargetSpecies -> getProperty(name)
    is AdministrableProductDefinition.RouteOfAdministration.TargetSpecies.WithdrawalPeriod ->
      getProperty(name)
    is AllergyIntolerance.Reaction -> getProperty(name)
    is PlanDefinition.Goal -> getProperty(name)
    is PlanDefinition.Goal.Target -> getProperty(name)
    is PlanDefinition.Action -> getProperty(name)
    is PlanDefinition.Action.Condition -> getProperty(name)
    is PlanDefinition.Action.RelatedAction -> getProperty(name)
    is PlanDefinition.Action.Participant -> getProperty(name)
    is PlanDefinition.Action.DynamicValue -> getProperty(name)
    is ClinicalImpression.Investigation -> getProperty(name)
    is ClinicalImpression.Finding -> getProperty(name)
    is Subscription.Channel -> getProperty(name)
    is CareTeam.Participant -> getProperty(name)
    is Device.UdiCarrier -> getProperty(name)
    is Device.DeviceName -> getProperty(name)
    is Device.Specialization -> getProperty(name)
    is Device.Version -> getProperty(name)
    is Device.Property -> getProperty(name)
    is NutritionProduct.Nutrient -> getProperty(name)
    is NutritionProduct.Ingredient -> getProperty(name)
    is NutritionProduct.ProductCharacteristic -> getProperty(name)
    is NutritionProduct.Instance -> getProperty(name)
    is Consent.Policy -> getProperty(name)
    is Consent.Verification -> getProperty(name)
    is Consent.Provision -> getProperty(name)
    is Consent.Provision.Actor -> getProperty(name)
    is Consent.Provision.Data -> getProperty(name)
    is MedicinalProductDefinition.Contact -> getProperty(name)
    is MedicinalProductDefinition.Name -> getProperty(name)
    is MedicinalProductDefinition.Name.NamePart -> getProperty(name)
    is MedicinalProductDefinition.Name.CountryLanguage -> getProperty(name)
    is MedicinalProductDefinition.CrossReference -> getProperty(name)
    is MedicinalProductDefinition.Operation -> getProperty(name)
    is MedicinalProductDefinition.Characteristic -> getProperty(name)
    is Communication.Payload -> getProperty(name)
    is StructureMap.Structure -> getProperty(name)
    else -> null
  }

private fun BackboneElement.getProperty3(name: String): Any? =
  when (this) {
    is StructureMap.Group -> getProperty(name)
    is StructureMap.Group.Input -> getProperty(name)
    is StructureMap.Group.Rule -> getProperty(name)
    is StructureMap.Group.Rule.Source -> getProperty(name)
    is StructureMap.Group.Rule.Target -> getProperty(name)
    is StructureMap.Group.Rule.Target.Parameter -> getProperty(name)
    is StructureMap.Group.Rule.Dependent -> getProperty(name)
    is Task.Restriction -> getProperty(name)
    is Task.Input -> getProperty(name)
    is Task.Output -> getProperty(name)
    is EvidenceReport.Subject -> getProperty(name)
    is EvidenceReport.Subject.Characteristic -> getProperty(name)
    is EvidenceReport.RelatesTo -> getProperty(name)
    is EvidenceReport.Section -> getProperty(name)
    is Practitioner.Qualification -> getProperty(name)
    is Ingredient.Manufacturer -> getProperty(name)
    is Ingredient.Substance -> getProperty(name)
    is Ingredient.Substance.Strength -> getProperty(name)
    is Ingredient.Substance.Strength.ReferenceStrength -> getProperty(name)
    is Observation.ReferenceRange -> getProperty(name)
    is Observation.Component -> getProperty(name)
    is DocumentReference.RelatesTo -> getProperty(name)
    is DocumentReference.Content -> getProperty(name)
    is DocumentReference.Context -> getProperty(name)
    is OperationOutcome.Issue -> getProperty(name)
    is MedicationDispense.Performer -> getProperty(name)
    is MedicationDispense.Substitution -> getProperty(name)
    is Account.Coverage -> getProperty(name)
    is Account.Guarantor -> getProperty(name)
    is Procedure.Performer -> getProperty(name)
    is Procedure.FocalDevice -> getProperty(name)
    is AdverseEvent.SuspectEntity -> getProperty(name)
    is AdverseEvent.SuspectEntity.Causality -> getProperty(name)
    else -> null
  }

internal fun BackboneElement.getProperty(name: String): Any? {
  getProperty0(name)?.let {
    return it
  }
  getProperty1(name)?.let {
    return it
  }
  getProperty2(name)?.let {
    return it
  }
  getProperty3(name)?.let {
    return it
  }
  return null
}

private fun BackboneElement.hasProperty0(name: String): Boolean =
  when (this) {
    is SubscriptionTopic.ResourceTrigger -> hasProperty(name)
    is SubscriptionTopic.ResourceTrigger.QueryCriteria -> hasProperty(name)
    is SubscriptionTopic.EventTrigger -> hasProperty(name)
    is SubscriptionTopic.CanFilterBy -> hasProperty(name)
    is SubscriptionTopic.NotificationShape -> hasProperty(name)
    is ExampleScenario.Actor -> hasProperty(name)
    is ExampleScenario.Instance -> hasProperty(name)
    is ExampleScenario.Instance.Version -> hasProperty(name)
    is ExampleScenario.Instance.ContainedInstance -> hasProperty(name)
    is ExampleScenario.Process -> hasProperty(name)
    is ExampleScenario.Process.Step -> hasProperty(name)
    is ExampleScenario.Process.Step.Operation -> hasProperty(name)
    is ExampleScenario.Process.Step.Alternative -> hasProperty(name)
    is Appointment.Participant -> hasProperty(name)
    is Condition.Stage -> hasProperty(name)
    is Condition.Evidence -> hasProperty(name)
    is R4bList.Entry -> hasProperty(name)
    is ChargeItem.Performer -> hasProperty(name)
    is VerificationResult.PrimarySource -> hasProperty(name)
    is VerificationResult.Attestation -> hasProperty(name)
    is VerificationResult.Validator -> hasProperty(name)
    is SupplyDelivery.SuppliedItem -> hasProperty(name)
    is Composition.Attester -> hasProperty(name)
    is Composition.RelatesTo -> hasProperty(name)
    is Composition.Event -> hasProperty(name)
    is Composition.Section -> hasProperty(name)
    is Encounter.StatusHistory -> hasProperty(name)
    is Encounter.ClassHistory -> hasProperty(name)
    is Encounter.Participant -> hasProperty(name)
    is Encounter.Diagnosis -> hasProperty(name)
    is Encounter.Hospitalization -> hasProperty(name)
    is Encounter.Location -> hasProperty(name)
    is MedicationAdministration.Performer -> hasProperty(name)
    is MedicationAdministration.Dosage -> hasProperty(name)
    is DocumentManifest.Related -> hasProperty(name)
    is Claim.Related -> hasProperty(name)
    is Claim.Payee -> hasProperty(name)
    is Claim.CareTeam -> hasProperty(name)
    is Claim.SupportingInfo -> hasProperty(name)
    is Claim.Diagnosis -> hasProperty(name)
    is Claim.Procedure -> hasProperty(name)
    is Claim.Insurance -> hasProperty(name)
    is Claim.Accident -> hasProperty(name)
    is Claim.Item -> hasProperty(name)
    is Claim.Item.Detail -> hasProperty(name)
    is Claim.Item.Detail.SubDetail -> hasProperty(name)
    is DeviceMetric.Calibration -> hasProperty(name)
    is AuditEvent.Agent -> hasProperty(name)
    is AuditEvent.Agent.Network -> hasProperty(name)
    is AuditEvent.Source -> hasProperty(name)
    is AuditEvent.Entity -> hasProperty(name)
    is AuditEvent.Entity.Detail -> hasProperty(name)
    is CarePlan.Activity -> hasProperty(name)
    is CarePlan.Activity.Detail -> hasProperty(name)
    is Linkage.Item -> hasProperty(name)
    is CoverageEligibilityResponse.Insurance -> hasProperty(name)
    is CoverageEligibilityResponse.Insurance.Item -> hasProperty(name)
    is CoverageEligibilityResponse.Insurance.Item.Benefit -> hasProperty(name)
    is CoverageEligibilityResponse.Error -> hasProperty(name)
    is QuestionnaireResponse.Item -> hasProperty(name)
    is QuestionnaireResponse.Item.Answer -> hasProperty(name)
    is Location.Position -> hasProperty(name)
    is Location.HoursOfOperation -> hasProperty(name)
    is InsurancePlan.Contact -> hasProperty(name)
    is InsurancePlan.Coverage -> hasProperty(name)
    is InsurancePlan.Coverage.Benefit -> hasProperty(name)
    is InsurancePlan.Coverage.Benefit.Limit -> hasProperty(name)
    is InsurancePlan.Plan -> hasProperty(name)
    is InsurancePlan.Plan.GeneralCost -> hasProperty(name)
    is InsurancePlan.Plan.SpecificCost -> hasProperty(name)
    is InsurancePlan.Plan.SpecificCost.Benefit -> hasProperty(name)
    is InsurancePlan.Plan.SpecificCost.Benefit.Cost -> hasProperty(name)
    is Citation.Summary -> hasProperty(name)
    is Citation.Classification -> hasProperty(name)
    is Citation.StatusDate -> hasProperty(name)
    is Citation.RelatesTo -> hasProperty(name)
    is Citation.CitedArtifact -> hasProperty(name)
    is Citation.CitedArtifact.Version -> hasProperty(name)
    is Citation.CitedArtifact.StatusDate -> hasProperty(name)
    is Citation.CitedArtifact.Title -> hasProperty(name)
    is Citation.CitedArtifact.Abstract -> hasProperty(name)
    is Citation.CitedArtifact.Part -> hasProperty(name)
    is Citation.CitedArtifact.RelatesTo -> hasProperty(name)
    is Citation.CitedArtifact.PublicationForm -> hasProperty(name)
    is Citation.CitedArtifact.PublicationForm.PublishedIn -> hasProperty(name)
    is Citation.CitedArtifact.PublicationForm.PeriodicRelease -> hasProperty(name)
    is Citation.CitedArtifact.PublicationForm.PeriodicRelease.DateOfPublication -> hasProperty(name)
    is Citation.CitedArtifact.WebLocation -> hasProperty(name)
    is Citation.CitedArtifact.Classification -> hasProperty(name)
    is Citation.CitedArtifact.Classification.WhoClassified -> hasProperty(name)
    is Citation.CitedArtifact.Contributorship -> hasProperty(name)
    is Citation.CitedArtifact.Contributorship.Entry -> hasProperty(name)
    is Citation.CitedArtifact.Contributorship.Entry.AffiliationInfo -> hasProperty(name)
    is Citation.CitedArtifact.Contributorship.Entry.ContributionInstance -> hasProperty(name)
    is Citation.CitedArtifact.Contributorship.Summary -> hasProperty(name)
    is SubscriptionStatus.NotificationEvent -> hasProperty(name)
    is Measure.Group -> hasProperty(name)
    is Measure.Group.Population -> hasProperty(name)
    is Measure.Group.Stratifier -> hasProperty(name)
    is Measure.Group.Stratifier.Component -> hasProperty(name)
    is Measure.SupplementalData -> hasProperty(name)
    is ActivityDefinition.Participant -> hasProperty(name)
    is ActivityDefinition.DynamicValue -> hasProperty(name)
    is EpisodeOfCare.StatusHistory -> hasProperty(name)
    is EpisodeOfCare.Diagnosis -> hasProperty(name)
    is DeviceRequest.Parameter -> hasProperty(name)
    is CapabilityStatement.Software -> hasProperty(name)
    is CapabilityStatement.Implementation -> hasProperty(name)
    is CapabilityStatement.Rest -> hasProperty(name)
    is CapabilityStatement.Rest.Security -> hasProperty(name)
    is CapabilityStatement.Rest.Resource -> hasProperty(name)
    is CapabilityStatement.Rest.Resource.Interaction -> hasProperty(name)
    is CapabilityStatement.Rest.Resource.SearchParam -> hasProperty(name)
    is CapabilityStatement.Rest.Resource.Operation -> hasProperty(name)
    is CapabilityStatement.Rest.Interaction -> hasProperty(name)
    is CapabilityStatement.Messaging -> hasProperty(name)
    is CapabilityStatement.Messaging.Endpoint -> hasProperty(name)
    is CapabilityStatement.Messaging.SupportedMessage -> hasProperty(name)
    is CapabilityStatement.Document -> hasProperty(name)
    is Substance.Instance -> hasProperty(name)
    is Substance.Ingredient -> hasProperty(name)
    is CatalogEntry.RelatedEntry -> hasProperty(name)
    is Group.Characteristic -> hasProperty(name)
    is Group.Member -> hasProperty(name)
    is ImagingStudy.Series -> hasProperty(name)
    is ImagingStudy.Series.Performer -> hasProperty(name)
    is ImagingStudy.Series.Instance -> hasProperty(name)
    is Organization.Contact -> hasProperty(name)
    is MolecularSequence.ReferenceSeq -> hasProperty(name)
    is MolecularSequence.Variant -> hasProperty(name)
    is MolecularSequence.Quality -> hasProperty(name)
    is MolecularSequence.Quality.Roc -> hasProperty(name)
    is MolecularSequence.Repository -> hasProperty(name)
    is MolecularSequence.StructureVariant -> hasProperty(name)
    is MolecularSequence.StructureVariant.Outer -> hasProperty(name)
    is MolecularSequence.StructureVariant.Inner -> hasProperty(name)
    is RegulatedAuthorization.Case -> hasProperty(name)
    is ChargeItemDefinition.Applicability -> hasProperty(name)
    is ChargeItemDefinition.PropertyGroup -> hasProperty(name)
    is ChargeItemDefinition.PropertyGroup.PriceComponent -> hasProperty(name)
    is Questionnaire.Item -> hasProperty(name)
    is Questionnaire.Item.EnableWhen -> hasProperty(name)
    is Questionnaire.Item.AnswerOption -> hasProperty(name)
    is Questionnaire.Item.Initial -> hasProperty(name)
    is TestScript.Origin -> hasProperty(name)
    is TestScript.Destination -> hasProperty(name)
    is TestScript.Metadata -> hasProperty(name)
    is TestScript.Metadata.Link -> hasProperty(name)
    is TestScript.Metadata.Capability -> hasProperty(name)
    is TestScript.Fixture -> hasProperty(name)
    else -> false
  }

private fun BackboneElement.hasProperty1(name: String): Boolean =
  when (this) {
    is TestScript.Variable -> hasProperty(name)
    is TestScript.Setup -> hasProperty(name)
    is TestScript.Setup.Action -> hasProperty(name)
    is TestScript.Setup.Action.Operation -> hasProperty(name)
    is TestScript.Setup.Action.Operation.RequestHeader -> hasProperty(name)
    is TestScript.Setup.Action.Assert -> hasProperty(name)
    is TestScript.Test -> hasProperty(name)
    is TestScript.Test.Action -> hasProperty(name)
    is TestScript.Teardown -> hasProperty(name)
    is TestScript.Teardown.Action -> hasProperty(name)
    is ResearchStudy.Arm -> hasProperty(name)
    is ResearchStudy.Objective -> hasProperty(name)
    is PractitionerRole.AvailableTime -> hasProperty(name)
    is PractitionerRole.NotAvailable -> hasProperty(name)
    is TestReport.Participant -> hasProperty(name)
    is TestReport.Setup -> hasProperty(name)
    is TestReport.Setup.Action -> hasProperty(name)
    is TestReport.Setup.Action.Operation -> hasProperty(name)
    is TestReport.Setup.Action.Assert -> hasProperty(name)
    is TestReport.Test -> hasProperty(name)
    is TestReport.Test.Action -> hasProperty(name)
    is TestReport.Teardown -> hasProperty(name)
    is TestReport.Teardown.Action -> hasProperty(name)
    is MeasureReport.Group -> hasProperty(name)
    is MeasureReport.Group.Population -> hasProperty(name)
    is MeasureReport.Group.Stratifier -> hasProperty(name)
    is MeasureReport.Group.Stratifier.Stratum -> hasProperty(name)
    is MeasureReport.Group.Stratifier.Stratum.Component -> hasProperty(name)
    is MeasureReport.Group.Stratifier.Stratum.Population -> hasProperty(name)
    is SubstanceDefinition.Moiety -> hasProperty(name)
    is SubstanceDefinition.Property -> hasProperty(name)
    is SubstanceDefinition.MolecularWeight -> hasProperty(name)
    is SubstanceDefinition.Structure -> hasProperty(name)
    is SubstanceDefinition.Structure.Representation -> hasProperty(name)
    is SubstanceDefinition.Code -> hasProperty(name)
    is SubstanceDefinition.Name -> hasProperty(name)
    is SubstanceDefinition.Name.Official -> hasProperty(name)
    is SubstanceDefinition.Relationship -> hasProperty(name)
    is SubstanceDefinition.SourceMaterial -> hasProperty(name)
    is SupplyRequest.Parameter -> hasProperty(name)
    is Provenance.Agent -> hasProperty(name)
    is Provenance.Entity -> hasProperty(name)
    is RiskAssessment.Prediction -> hasProperty(name)
    is Parameters.Parameter -> hasProperty(name)
    is HealthcareService.Eligibility -> hasProperty(name)
    is HealthcareService.AvailableTime -> hasProperty(name)
    is HealthcareService.NotAvailable -> hasProperty(name)
    is RelatedPerson.Communication -> hasProperty(name)
    is Evidence.VariableDefinition -> hasProperty(name)
    is Evidence.Statistic -> hasProperty(name)
    is Evidence.Statistic.SampleSize -> hasProperty(name)
    is Evidence.Statistic.AttributeEstimate -> hasProperty(name)
    is Evidence.Statistic.ModelCharacteristic -> hasProperty(name)
    is Evidence.Statistic.ModelCharacteristic.Variable -> hasProperty(name)
    is Evidence.Certainty -> hasProperty(name)
    is NamingSystem.UniqueId -> hasProperty(name)
    is VisionPrescription.LensSpecification -> hasProperty(name)
    is VisionPrescription.LensSpecification.Prism -> hasProperty(name)
    is ExplanationOfBenefit.Related -> hasProperty(name)
    is ExplanationOfBenefit.Payee -> hasProperty(name)
    is ExplanationOfBenefit.CareTeam -> hasProperty(name)
    is ExplanationOfBenefit.SupportingInfo -> hasProperty(name)
    is ExplanationOfBenefit.Diagnosis -> hasProperty(name)
    is ExplanationOfBenefit.Procedure -> hasProperty(name)
    is ExplanationOfBenefit.Insurance -> hasProperty(name)
    is ExplanationOfBenefit.Accident -> hasProperty(name)
    is ExplanationOfBenefit.Item -> hasProperty(name)
    is ExplanationOfBenefit.Item.Adjudication -> hasProperty(name)
    is ExplanationOfBenefit.Item.Detail -> hasProperty(name)
    is ExplanationOfBenefit.Item.Detail.SubDetail -> hasProperty(name)
    is ExplanationOfBenefit.AddItem -> hasProperty(name)
    is ExplanationOfBenefit.AddItem.Detail -> hasProperty(name)
    is ExplanationOfBenefit.AddItem.Detail.SubDetail -> hasProperty(name)
    is ExplanationOfBenefit.Total -> hasProperty(name)
    is ExplanationOfBenefit.Payment -> hasProperty(name)
    is ExplanationOfBenefit.ProcessNote -> hasProperty(name)
    is ExplanationOfBenefit.BenefitBalance -> hasProperty(name)
    is ExplanationOfBenefit.BenefitBalance.Financial -> hasProperty(name)
    is PackagedProductDefinition.LegalStatusOfSupply -> hasProperty(name)
    is PackagedProductDefinition.Package -> hasProperty(name)
    is PackagedProductDefinition.Package.ShelfLifeStorage -> hasProperty(name)
    is PackagedProductDefinition.Package.Property -> hasProperty(name)
    is PackagedProductDefinition.Package.ContainedItem -> hasProperty(name)
    is Patient.Contact -> hasProperty(name)
    is Patient.Communication -> hasProperty(name)
    is Patient.Link -> hasProperty(name)
    is ManufacturedItemDefinition.Property -> hasProperty(name)
    is Specimen.Collection -> hasProperty(name)
    is Specimen.Processing -> hasProperty(name)
    is Specimen.Container -> hasProperty(name)
    is FamilyMemberHistory.Condition -> hasProperty(name)
    is ResearchElementDefinition.Characteristic -> hasProperty(name)
    is OperationDefinition.Parameter -> hasProperty(name)
    is OperationDefinition.Parameter.Binding -> hasProperty(name)
    is OperationDefinition.Parameter.ReferencedFrom -> hasProperty(name)
    is OperationDefinition.Overload -> hasProperty(name)
    is GraphDefinition.Link -> hasProperty(name)
    is GraphDefinition.Link.Target -> hasProperty(name)
    is GraphDefinition.Link.Target.Compartment -> hasProperty(name)
    is Medication.Ingredient -> hasProperty(name)
    is Medication.Batch -> hasProperty(name)
    is DiagnosticReport.Media -> hasProperty(name)
    is RequestGroup.Action -> hasProperty(name)
    is RequestGroup.Action.Condition -> hasProperty(name)
    is RequestGroup.Action.RelatedAction -> hasProperty(name)
    is MessageHeader.Destination -> hasProperty(name)
    is MessageHeader.Source -> hasProperty(name)
    is MessageHeader.Response -> hasProperty(name)
    is DeviceDefinition.UdiDeviceIdentifier -> hasProperty(name)
    is DeviceDefinition.DeviceName -> hasProperty(name)
    is DeviceDefinition.Specialization -> hasProperty(name)
    is DeviceDefinition.Capability -> hasProperty(name)
    is DeviceDefinition.Property -> hasProperty(name)
    is DeviceDefinition.Material -> hasProperty(name)
    is Goal.Target -> hasProperty(name)
    is ObservationDefinition.QuantitativeDetails -> hasProperty(name)
    is ObservationDefinition.QualifiedInterval -> hasProperty(name)
    is Immunization.Performer -> hasProperty(name)
    is Immunization.Education -> hasProperty(name)
    is Immunization.Reaction -> hasProperty(name)
    is Immunization.ProtocolApplied -> hasProperty(name)
    is ValueSet.Compose -> hasProperty(name)
    is ValueSet.Compose.Include -> hasProperty(name)
    is ValueSet.Compose.Include.Concept -> hasProperty(name)
    is ValueSet.Compose.Include.Concept.Designation -> hasProperty(name)
    is ValueSet.Compose.Include.Filter -> hasProperty(name)
    is ValueSet.Expansion -> hasProperty(name)
    is ValueSet.Expansion.Parameter -> hasProperty(name)
    is ValueSet.Expansion.Contains -> hasProperty(name)
    is ClaimResponse.Item -> hasProperty(name)
    is ClaimResponse.Item.Adjudication -> hasProperty(name)
    is ClaimResponse.Item.Detail -> hasProperty(name)
    is ClaimResponse.Item.Detail.SubDetail -> hasProperty(name)
    is ClaimResponse.AddItem -> hasProperty(name)
    is ClaimResponse.AddItem.Detail -> hasProperty(name)
    is ClaimResponse.AddItem.Detail.SubDetail -> hasProperty(name)
    is ClaimResponse.Total -> hasProperty(name)
    is ClaimResponse.Payment -> hasProperty(name)
    is ClaimResponse.ProcessNote -> hasProperty(name)
    is ClaimResponse.Insurance -> hasProperty(name)
    is ClaimResponse.Error -> hasProperty(name)
    is Contract.ContentDefinition -> hasProperty(name)
    is Contract.Term -> hasProperty(name)
    is Contract.Term.SecurityLabel -> hasProperty(name)
    is Contract.Term.Offer -> hasProperty(name)
    is Contract.Term.Offer.Party -> hasProperty(name)
    is Contract.Term.Offer.Answer -> hasProperty(name)
    is Contract.Term.Asset -> hasProperty(name)
    is Contract.Term.Asset.Context -> hasProperty(name)
    is Contract.Term.Asset.ValuedItem -> hasProperty(name)
    else -> false
  }

private fun BackboneElement.hasProperty2(name: String): Boolean =
  when (this) {
    is Contract.Term.Action -> hasProperty(name)
    is Contract.Term.Action.Subject -> hasProperty(name)
    is Contract.Signer -> hasProperty(name)
    is Contract.Friendly -> hasProperty(name)
    is Contract.Legal -> hasProperty(name)
    is Contract.Rule -> hasProperty(name)
    is BiologicallyDerivedProduct.Collection -> hasProperty(name)
    is BiologicallyDerivedProduct.Processing -> hasProperty(name)
    is BiologicallyDerivedProduct.Manipulation -> hasProperty(name)
    is BiologicallyDerivedProduct.Storage -> hasProperty(name)
    is TerminologyCapabilities.Software -> hasProperty(name)
    is TerminologyCapabilities.Implementation -> hasProperty(name)
    is TerminologyCapabilities.CodeSystem -> hasProperty(name)
    is TerminologyCapabilities.CodeSystem.Version -> hasProperty(name)
    is TerminologyCapabilities.CodeSystem.Version.Filter -> hasProperty(name)
    is TerminologyCapabilities.Expansion -> hasProperty(name)
    is TerminologyCapabilities.Expansion.Parameter -> hasProperty(name)
    is TerminologyCapabilities.ValidateCode -> hasProperty(name)
    is TerminologyCapabilities.Translation -> hasProperty(name)
    is TerminologyCapabilities.Closure -> hasProperty(name)
    is ClinicalUseDefinition.Contraindication -> hasProperty(name)
    is ClinicalUseDefinition.Contraindication.OtherTherapy -> hasProperty(name)
    is ClinicalUseDefinition.Indication -> hasProperty(name)
    is ClinicalUseDefinition.Interaction -> hasProperty(name)
    is ClinicalUseDefinition.Interaction.Interactant -> hasProperty(name)
    is ClinicalUseDefinition.UndesirableEffect -> hasProperty(name)
    is ClinicalUseDefinition.Warning -> hasProperty(name)
    is SpecimenDefinition.TypeTested -> hasProperty(name)
    is SpecimenDefinition.TypeTested.Container -> hasProperty(name)
    is SpecimenDefinition.TypeTested.Container.Additive -> hasProperty(name)
    is SpecimenDefinition.TypeTested.Handling -> hasProperty(name)
    is ConceptMap.Group -> hasProperty(name)
    is ConceptMap.Group.Element -> hasProperty(name)
    is ConceptMap.Group.Element.Target -> hasProperty(name)
    is ConceptMap.Group.Element.Target.DependsOn -> hasProperty(name)
    is ConceptMap.Group.Unmapped -> hasProperty(name)
    is Invoice.Participant -> hasProperty(name)
    is Invoice.LineItem -> hasProperty(name)
    is Invoice.LineItem.PriceComponent -> hasProperty(name)
    is StructureDefinition.Mapping -> hasProperty(name)
    is StructureDefinition.Context -> hasProperty(name)
    is StructureDefinition.Snapshot -> hasProperty(name)
    is StructureDefinition.Differential -> hasProperty(name)
    is CommunicationRequest.Payload -> hasProperty(name)
    is DetectedIssue.Evidence -> hasProperty(name)
    is DetectedIssue.Mitigation -> hasProperty(name)
    is EvidenceVariable.Characteristic -> hasProperty(name)
    is EvidenceVariable.Characteristic.TimeFromStart -> hasProperty(name)
    is EvidenceVariable.Category -> hasProperty(name)
    is Bundle.Link -> hasProperty(name)
    is Bundle.Entry -> hasProperty(name)
    is Bundle.Entry.Search -> hasProperty(name)
    is Bundle.Entry.Request -> hasProperty(name)
    is Bundle.Entry.Response -> hasProperty(name)
    is MessageDefinition.Focus -> hasProperty(name)
    is MessageDefinition.AllowedResponse -> hasProperty(name)
    is ImplementationGuide.DependsOn -> hasProperty(name)
    is ImplementationGuide.Global -> hasProperty(name)
    is ImplementationGuide.Definition -> hasProperty(name)
    is ImplementationGuide.Definition.Grouping -> hasProperty(name)
    is ImplementationGuide.Definition.Resource -> hasProperty(name)
    is ImplementationGuide.Definition.Page -> hasProperty(name)
    is ImplementationGuide.Definition.Parameter -> hasProperty(name)
    is ImplementationGuide.Definition.Template -> hasProperty(name)
    is ImplementationGuide.Manifest -> hasProperty(name)
    is ImplementationGuide.Manifest.Resource -> hasProperty(name)
    is ImplementationGuide.Manifest.Page -> hasProperty(name)
    is NutritionOrder.OralDiet -> hasProperty(name)
    is NutritionOrder.OralDiet.Nutrient -> hasProperty(name)
    is NutritionOrder.OralDiet.Texture -> hasProperty(name)
    is NutritionOrder.Supplement -> hasProperty(name)
    is NutritionOrder.EnteralFormula -> hasProperty(name)
    is NutritionOrder.EnteralFormula.Administration -> hasProperty(name)
    is CoverageEligibilityRequest.SupportingInfo -> hasProperty(name)
    is CoverageEligibilityRequest.Insurance -> hasProperty(name)
    is CoverageEligibilityRequest.Item -> hasProperty(name)
    is CoverageEligibilityRequest.Item.Diagnosis -> hasProperty(name)
    is CodeSystem.Filter -> hasProperty(name)
    is CodeSystem.Property -> hasProperty(name)
    is CodeSystem.Concept -> hasProperty(name)
    is CodeSystem.Concept.Designation -> hasProperty(name)
    is CodeSystem.Concept.Property -> hasProperty(name)
    is MedicationRequest.DispenseRequest -> hasProperty(name)
    is MedicationRequest.DispenseRequest.InitialFill -> hasProperty(name)
    is MedicationRequest.Substitution -> hasProperty(name)
    is ImmunizationRecommendation.Recommendation -> hasProperty(name)
    is ImmunizationRecommendation.Recommendation.DateCriterion -> hasProperty(name)
    is CompartmentDefinition.Resource -> hasProperty(name)
    is Coverage.Class -> hasProperty(name)
    is Coverage.CostToBeneficiary -> hasProperty(name)
    is Coverage.CostToBeneficiary.Exception -> hasProperty(name)
    is PaymentReconciliation.Detail -> hasProperty(name)
    is PaymentReconciliation.ProcessNote -> hasProperty(name)
    is MedicationKnowledge.RelatedMedicationKnowledge -> hasProperty(name)
    is MedicationKnowledge.Monograph -> hasProperty(name)
    is MedicationKnowledge.Ingredient -> hasProperty(name)
    is MedicationKnowledge.Cost -> hasProperty(name)
    is MedicationKnowledge.MonitoringProgram -> hasProperty(name)
    is MedicationKnowledge.AdministrationGuidelines -> hasProperty(name)
    is MedicationKnowledge.AdministrationGuidelines.Dosage -> hasProperty(name)
    is MedicationKnowledge.AdministrationGuidelines.PatientCharacteristics -> hasProperty(name)
    is MedicationKnowledge.MedicineClassification -> hasProperty(name)
    is MedicationKnowledge.Packaging -> hasProperty(name)
    is MedicationKnowledge.DrugCharacteristic -> hasProperty(name)
    is MedicationKnowledge.Regulatory -> hasProperty(name)
    is MedicationKnowledge.Regulatory.Substitution -> hasProperty(name)
    is MedicationKnowledge.Regulatory.Schedule -> hasProperty(name)
    is MedicationKnowledge.Regulatory.MaxDispense -> hasProperty(name)
    is MedicationKnowledge.Kinetics -> hasProperty(name)
    is SearchParameter.Component -> hasProperty(name)
    is Person.Link -> hasProperty(name)
    is AdministrableProductDefinition.Property -> hasProperty(name)
    is AdministrableProductDefinition.RouteOfAdministration -> hasProperty(name)
    is AdministrableProductDefinition.RouteOfAdministration.TargetSpecies -> hasProperty(name)
    is AdministrableProductDefinition.RouteOfAdministration.TargetSpecies.WithdrawalPeriod ->
      hasProperty(name)
    is AllergyIntolerance.Reaction -> hasProperty(name)
    is PlanDefinition.Goal -> hasProperty(name)
    is PlanDefinition.Goal.Target -> hasProperty(name)
    is PlanDefinition.Action -> hasProperty(name)
    is PlanDefinition.Action.Condition -> hasProperty(name)
    is PlanDefinition.Action.RelatedAction -> hasProperty(name)
    is PlanDefinition.Action.Participant -> hasProperty(name)
    is PlanDefinition.Action.DynamicValue -> hasProperty(name)
    is ClinicalImpression.Investigation -> hasProperty(name)
    is ClinicalImpression.Finding -> hasProperty(name)
    is Subscription.Channel -> hasProperty(name)
    is CareTeam.Participant -> hasProperty(name)
    is Device.UdiCarrier -> hasProperty(name)
    is Device.DeviceName -> hasProperty(name)
    is Device.Specialization -> hasProperty(name)
    is Device.Version -> hasProperty(name)
    is Device.Property -> hasProperty(name)
    is NutritionProduct.Nutrient -> hasProperty(name)
    is NutritionProduct.Ingredient -> hasProperty(name)
    is NutritionProduct.ProductCharacteristic -> hasProperty(name)
    is NutritionProduct.Instance -> hasProperty(name)
    is Consent.Policy -> hasProperty(name)
    is Consent.Verification -> hasProperty(name)
    is Consent.Provision -> hasProperty(name)
    is Consent.Provision.Actor -> hasProperty(name)
    is Consent.Provision.Data -> hasProperty(name)
    is MedicinalProductDefinition.Contact -> hasProperty(name)
    is MedicinalProductDefinition.Name -> hasProperty(name)
    is MedicinalProductDefinition.Name.NamePart -> hasProperty(name)
    is MedicinalProductDefinition.Name.CountryLanguage -> hasProperty(name)
    is MedicinalProductDefinition.CrossReference -> hasProperty(name)
    is MedicinalProductDefinition.Operation -> hasProperty(name)
    is MedicinalProductDefinition.Characteristic -> hasProperty(name)
    is Communication.Payload -> hasProperty(name)
    is StructureMap.Structure -> hasProperty(name)
    else -> false
  }

private fun BackboneElement.hasProperty3(name: String): Boolean =
  when (this) {
    is StructureMap.Group -> hasProperty(name)
    is StructureMap.Group.Input -> hasProperty(name)
    is StructureMap.Group.Rule -> hasProperty(name)
    is StructureMap.Group.Rule.Source -> hasProperty(name)
    is StructureMap.Group.Rule.Target -> hasProperty(name)
    is StructureMap.Group.Rule.Target.Parameter -> hasProperty(name)
    is StructureMap.Group.Rule.Dependent -> hasProperty(name)
    is Task.Restriction -> hasProperty(name)
    is Task.Input -> hasProperty(name)
    is Task.Output -> hasProperty(name)
    is EvidenceReport.Subject -> hasProperty(name)
    is EvidenceReport.Subject.Characteristic -> hasProperty(name)
    is EvidenceReport.RelatesTo -> hasProperty(name)
    is EvidenceReport.Section -> hasProperty(name)
    is Practitioner.Qualification -> hasProperty(name)
    is Ingredient.Manufacturer -> hasProperty(name)
    is Ingredient.Substance -> hasProperty(name)
    is Ingredient.Substance.Strength -> hasProperty(name)
    is Ingredient.Substance.Strength.ReferenceStrength -> hasProperty(name)
    is Observation.ReferenceRange -> hasProperty(name)
    is Observation.Component -> hasProperty(name)
    is DocumentReference.RelatesTo -> hasProperty(name)
    is DocumentReference.Content -> hasProperty(name)
    is DocumentReference.Context -> hasProperty(name)
    is OperationOutcome.Issue -> hasProperty(name)
    is MedicationDispense.Performer -> hasProperty(name)
    is MedicationDispense.Substitution -> hasProperty(name)
    is Account.Coverage -> hasProperty(name)
    is Account.Guarantor -> hasProperty(name)
    is Procedure.Performer -> hasProperty(name)
    is Procedure.FocalDevice -> hasProperty(name)
    is AdverseEvent.SuspectEntity -> hasProperty(name)
    is AdverseEvent.SuspectEntity.Causality -> hasProperty(name)
    else -> false
  }

internal fun BackboneElement.hasProperty(name: String): Boolean {
  if (hasProperty0(name)) return true
  if (hasProperty1(name)) return true
  if (hasProperty2(name)) return true
  if (hasProperty3(name)) return true
  return false
}

private fun BackboneElement.getAllChildren0(): CollectionsList<Any> =
  when (this) {
    is SubscriptionTopic.ResourceTrigger -> getAllChildren()
    is SubscriptionTopic.ResourceTrigger.QueryCriteria -> getAllChildren()
    is SubscriptionTopic.EventTrigger -> getAllChildren()
    is SubscriptionTopic.CanFilterBy -> getAllChildren()
    is SubscriptionTopic.NotificationShape -> getAllChildren()
    is ExampleScenario.Actor -> getAllChildren()
    is ExampleScenario.Instance -> getAllChildren()
    is ExampleScenario.Instance.Version -> getAllChildren()
    is ExampleScenario.Instance.ContainedInstance -> getAllChildren()
    is ExampleScenario.Process -> getAllChildren()
    is ExampleScenario.Process.Step -> getAllChildren()
    is ExampleScenario.Process.Step.Operation -> getAllChildren()
    is ExampleScenario.Process.Step.Alternative -> getAllChildren()
    is Appointment.Participant -> getAllChildren()
    is Condition.Stage -> getAllChildren()
    is Condition.Evidence -> getAllChildren()
    is R4bList.Entry -> getAllChildren()
    is ChargeItem.Performer -> getAllChildren()
    is VerificationResult.PrimarySource -> getAllChildren()
    is VerificationResult.Attestation -> getAllChildren()
    is VerificationResult.Validator -> getAllChildren()
    is SupplyDelivery.SuppliedItem -> getAllChildren()
    is Composition.Attester -> getAllChildren()
    is Composition.RelatesTo -> getAllChildren()
    is Composition.Event -> getAllChildren()
    is Composition.Section -> getAllChildren()
    is Encounter.StatusHistory -> getAllChildren()
    is Encounter.ClassHistory -> getAllChildren()
    is Encounter.Participant -> getAllChildren()
    is Encounter.Diagnosis -> getAllChildren()
    is Encounter.Hospitalization -> getAllChildren()
    is Encounter.Location -> getAllChildren()
    is MedicationAdministration.Performer -> getAllChildren()
    is MedicationAdministration.Dosage -> getAllChildren()
    is DocumentManifest.Related -> getAllChildren()
    is Claim.Related -> getAllChildren()
    is Claim.Payee -> getAllChildren()
    is Claim.CareTeam -> getAllChildren()
    is Claim.SupportingInfo -> getAllChildren()
    is Claim.Diagnosis -> getAllChildren()
    is Claim.Procedure -> getAllChildren()
    is Claim.Insurance -> getAllChildren()
    is Claim.Accident -> getAllChildren()
    is Claim.Item -> getAllChildren()
    is Claim.Item.Detail -> getAllChildren()
    is Claim.Item.Detail.SubDetail -> getAllChildren()
    is DeviceMetric.Calibration -> getAllChildren()
    is AuditEvent.Agent -> getAllChildren()
    is AuditEvent.Agent.Network -> getAllChildren()
    is AuditEvent.Source -> getAllChildren()
    is AuditEvent.Entity -> getAllChildren()
    is AuditEvent.Entity.Detail -> getAllChildren()
    is CarePlan.Activity -> getAllChildren()
    is CarePlan.Activity.Detail -> getAllChildren()
    is Linkage.Item -> getAllChildren()
    is CoverageEligibilityResponse.Insurance -> getAllChildren()
    is CoverageEligibilityResponse.Insurance.Item -> getAllChildren()
    is CoverageEligibilityResponse.Insurance.Item.Benefit -> getAllChildren()
    is CoverageEligibilityResponse.Error -> getAllChildren()
    is QuestionnaireResponse.Item -> getAllChildren()
    is QuestionnaireResponse.Item.Answer -> getAllChildren()
    is Location.Position -> getAllChildren()
    is Location.HoursOfOperation -> getAllChildren()
    is InsurancePlan.Contact -> getAllChildren()
    is InsurancePlan.Coverage -> getAllChildren()
    is InsurancePlan.Coverage.Benefit -> getAllChildren()
    is InsurancePlan.Coverage.Benefit.Limit -> getAllChildren()
    is InsurancePlan.Plan -> getAllChildren()
    is InsurancePlan.Plan.GeneralCost -> getAllChildren()
    is InsurancePlan.Plan.SpecificCost -> getAllChildren()
    is InsurancePlan.Plan.SpecificCost.Benefit -> getAllChildren()
    is InsurancePlan.Plan.SpecificCost.Benefit.Cost -> getAllChildren()
    is Citation.Summary -> getAllChildren()
    is Citation.Classification -> getAllChildren()
    is Citation.StatusDate -> getAllChildren()
    is Citation.RelatesTo -> getAllChildren()
    is Citation.CitedArtifact -> getAllChildren()
    is Citation.CitedArtifact.Version -> getAllChildren()
    is Citation.CitedArtifact.StatusDate -> getAllChildren()
    is Citation.CitedArtifact.Title -> getAllChildren()
    is Citation.CitedArtifact.Abstract -> getAllChildren()
    is Citation.CitedArtifact.Part -> getAllChildren()
    is Citation.CitedArtifact.RelatesTo -> getAllChildren()
    is Citation.CitedArtifact.PublicationForm -> getAllChildren()
    is Citation.CitedArtifact.PublicationForm.PublishedIn -> getAllChildren()
    is Citation.CitedArtifact.PublicationForm.PeriodicRelease -> getAllChildren()
    is Citation.CitedArtifact.PublicationForm.PeriodicRelease.DateOfPublication -> getAllChildren()
    is Citation.CitedArtifact.WebLocation -> getAllChildren()
    is Citation.CitedArtifact.Classification -> getAllChildren()
    is Citation.CitedArtifact.Classification.WhoClassified -> getAllChildren()
    is Citation.CitedArtifact.Contributorship -> getAllChildren()
    is Citation.CitedArtifact.Contributorship.Entry -> getAllChildren()
    is Citation.CitedArtifact.Contributorship.Entry.AffiliationInfo -> getAllChildren()
    is Citation.CitedArtifact.Contributorship.Entry.ContributionInstance -> getAllChildren()
    is Citation.CitedArtifact.Contributorship.Summary -> getAllChildren()
    is SubscriptionStatus.NotificationEvent -> getAllChildren()
    is Measure.Group -> getAllChildren()
    is Measure.Group.Population -> getAllChildren()
    is Measure.Group.Stratifier -> getAllChildren()
    is Measure.Group.Stratifier.Component -> getAllChildren()
    is Measure.SupplementalData -> getAllChildren()
    is ActivityDefinition.Participant -> getAllChildren()
    is ActivityDefinition.DynamicValue -> getAllChildren()
    is EpisodeOfCare.StatusHistory -> getAllChildren()
    is EpisodeOfCare.Diagnosis -> getAllChildren()
    is DeviceRequest.Parameter -> getAllChildren()
    is CapabilityStatement.Software -> getAllChildren()
    is CapabilityStatement.Implementation -> getAllChildren()
    is CapabilityStatement.Rest -> getAllChildren()
    is CapabilityStatement.Rest.Security -> getAllChildren()
    is CapabilityStatement.Rest.Resource -> getAllChildren()
    is CapabilityStatement.Rest.Resource.Interaction -> getAllChildren()
    is CapabilityStatement.Rest.Resource.SearchParam -> getAllChildren()
    is CapabilityStatement.Rest.Resource.Operation -> getAllChildren()
    is CapabilityStatement.Rest.Interaction -> getAllChildren()
    is CapabilityStatement.Messaging -> getAllChildren()
    is CapabilityStatement.Messaging.Endpoint -> getAllChildren()
    is CapabilityStatement.Messaging.SupportedMessage -> getAllChildren()
    is CapabilityStatement.Document -> getAllChildren()
    is Substance.Instance -> getAllChildren()
    is Substance.Ingredient -> getAllChildren()
    is CatalogEntry.RelatedEntry -> getAllChildren()
    is Group.Characteristic -> getAllChildren()
    is Group.Member -> getAllChildren()
    is ImagingStudy.Series -> getAllChildren()
    is ImagingStudy.Series.Performer -> getAllChildren()
    is ImagingStudy.Series.Instance -> getAllChildren()
    is Organization.Contact -> getAllChildren()
    is MolecularSequence.ReferenceSeq -> getAllChildren()
    is MolecularSequence.Variant -> getAllChildren()
    is MolecularSequence.Quality -> getAllChildren()
    is MolecularSequence.Quality.Roc -> getAllChildren()
    is MolecularSequence.Repository -> getAllChildren()
    is MolecularSequence.StructureVariant -> getAllChildren()
    is MolecularSequence.StructureVariant.Outer -> getAllChildren()
    is MolecularSequence.StructureVariant.Inner -> getAllChildren()
    is RegulatedAuthorization.Case -> getAllChildren()
    is ChargeItemDefinition.Applicability -> getAllChildren()
    is ChargeItemDefinition.PropertyGroup -> getAllChildren()
    is ChargeItemDefinition.PropertyGroup.PriceComponent -> getAllChildren()
    is Questionnaire.Item -> getAllChildren()
    is Questionnaire.Item.EnableWhen -> getAllChildren()
    is Questionnaire.Item.AnswerOption -> getAllChildren()
    is Questionnaire.Item.Initial -> getAllChildren()
    is TestScript.Origin -> getAllChildren()
    is TestScript.Destination -> getAllChildren()
    is TestScript.Metadata -> getAllChildren()
    is TestScript.Metadata.Link -> getAllChildren()
    is TestScript.Metadata.Capability -> getAllChildren()
    is TestScript.Fixture -> getAllChildren()
    else -> emptyList()
  }

private fun BackboneElement.getAllChildren1(): CollectionsList<Any> =
  when (this) {
    is TestScript.Variable -> getAllChildren()
    is TestScript.Setup -> getAllChildren()
    is TestScript.Setup.Action -> getAllChildren()
    is TestScript.Setup.Action.Operation -> getAllChildren()
    is TestScript.Setup.Action.Operation.RequestHeader -> getAllChildren()
    is TestScript.Setup.Action.Assert -> getAllChildren()
    is TestScript.Test -> getAllChildren()
    is TestScript.Test.Action -> getAllChildren()
    is TestScript.Teardown -> getAllChildren()
    is TestScript.Teardown.Action -> getAllChildren()
    is ResearchStudy.Arm -> getAllChildren()
    is ResearchStudy.Objective -> getAllChildren()
    is PractitionerRole.AvailableTime -> getAllChildren()
    is PractitionerRole.NotAvailable -> getAllChildren()
    is TestReport.Participant -> getAllChildren()
    is TestReport.Setup -> getAllChildren()
    is TestReport.Setup.Action -> getAllChildren()
    is TestReport.Setup.Action.Operation -> getAllChildren()
    is TestReport.Setup.Action.Assert -> getAllChildren()
    is TestReport.Test -> getAllChildren()
    is TestReport.Test.Action -> getAllChildren()
    is TestReport.Teardown -> getAllChildren()
    is TestReport.Teardown.Action -> getAllChildren()
    is MeasureReport.Group -> getAllChildren()
    is MeasureReport.Group.Population -> getAllChildren()
    is MeasureReport.Group.Stratifier -> getAllChildren()
    is MeasureReport.Group.Stratifier.Stratum -> getAllChildren()
    is MeasureReport.Group.Stratifier.Stratum.Component -> getAllChildren()
    is MeasureReport.Group.Stratifier.Stratum.Population -> getAllChildren()
    is SubstanceDefinition.Moiety -> getAllChildren()
    is SubstanceDefinition.Property -> getAllChildren()
    is SubstanceDefinition.MolecularWeight -> getAllChildren()
    is SubstanceDefinition.Structure -> getAllChildren()
    is SubstanceDefinition.Structure.Representation -> getAllChildren()
    is SubstanceDefinition.Code -> getAllChildren()
    is SubstanceDefinition.Name -> getAllChildren()
    is SubstanceDefinition.Name.Official -> getAllChildren()
    is SubstanceDefinition.Relationship -> getAllChildren()
    is SubstanceDefinition.SourceMaterial -> getAllChildren()
    is SupplyRequest.Parameter -> getAllChildren()
    is Provenance.Agent -> getAllChildren()
    is Provenance.Entity -> getAllChildren()
    is RiskAssessment.Prediction -> getAllChildren()
    is Parameters.Parameter -> getAllChildren()
    is HealthcareService.Eligibility -> getAllChildren()
    is HealthcareService.AvailableTime -> getAllChildren()
    is HealthcareService.NotAvailable -> getAllChildren()
    is RelatedPerson.Communication -> getAllChildren()
    is Evidence.VariableDefinition -> getAllChildren()
    is Evidence.Statistic -> getAllChildren()
    is Evidence.Statistic.SampleSize -> getAllChildren()
    is Evidence.Statistic.AttributeEstimate -> getAllChildren()
    is Evidence.Statistic.ModelCharacteristic -> getAllChildren()
    is Evidence.Statistic.ModelCharacteristic.Variable -> getAllChildren()
    is Evidence.Certainty -> getAllChildren()
    is NamingSystem.UniqueId -> getAllChildren()
    is VisionPrescription.LensSpecification -> getAllChildren()
    is VisionPrescription.LensSpecification.Prism -> getAllChildren()
    is ExplanationOfBenefit.Related -> getAllChildren()
    is ExplanationOfBenefit.Payee -> getAllChildren()
    is ExplanationOfBenefit.CareTeam -> getAllChildren()
    is ExplanationOfBenefit.SupportingInfo -> getAllChildren()
    is ExplanationOfBenefit.Diagnosis -> getAllChildren()
    is ExplanationOfBenefit.Procedure -> getAllChildren()
    is ExplanationOfBenefit.Insurance -> getAllChildren()
    is ExplanationOfBenefit.Accident -> getAllChildren()
    is ExplanationOfBenefit.Item -> getAllChildren()
    is ExplanationOfBenefit.Item.Adjudication -> getAllChildren()
    is ExplanationOfBenefit.Item.Detail -> getAllChildren()
    is ExplanationOfBenefit.Item.Detail.SubDetail -> getAllChildren()
    is ExplanationOfBenefit.AddItem -> getAllChildren()
    is ExplanationOfBenefit.AddItem.Detail -> getAllChildren()
    is ExplanationOfBenefit.AddItem.Detail.SubDetail -> getAllChildren()
    is ExplanationOfBenefit.Total -> getAllChildren()
    is ExplanationOfBenefit.Payment -> getAllChildren()
    is ExplanationOfBenefit.ProcessNote -> getAllChildren()
    is ExplanationOfBenefit.BenefitBalance -> getAllChildren()
    is ExplanationOfBenefit.BenefitBalance.Financial -> getAllChildren()
    is PackagedProductDefinition.LegalStatusOfSupply -> getAllChildren()
    is PackagedProductDefinition.Package -> getAllChildren()
    is PackagedProductDefinition.Package.ShelfLifeStorage -> getAllChildren()
    is PackagedProductDefinition.Package.Property -> getAllChildren()
    is PackagedProductDefinition.Package.ContainedItem -> getAllChildren()
    is Patient.Contact -> getAllChildren()
    is Patient.Communication -> getAllChildren()
    is Patient.Link -> getAllChildren()
    is ManufacturedItemDefinition.Property -> getAllChildren()
    is Specimen.Collection -> getAllChildren()
    is Specimen.Processing -> getAllChildren()
    is Specimen.Container -> getAllChildren()
    is FamilyMemberHistory.Condition -> getAllChildren()
    is ResearchElementDefinition.Characteristic -> getAllChildren()
    is OperationDefinition.Parameter -> getAllChildren()
    is OperationDefinition.Parameter.Binding -> getAllChildren()
    is OperationDefinition.Parameter.ReferencedFrom -> getAllChildren()
    is OperationDefinition.Overload -> getAllChildren()
    is GraphDefinition.Link -> getAllChildren()
    is GraphDefinition.Link.Target -> getAllChildren()
    is GraphDefinition.Link.Target.Compartment -> getAllChildren()
    is Medication.Ingredient -> getAllChildren()
    is Medication.Batch -> getAllChildren()
    is DiagnosticReport.Media -> getAllChildren()
    is RequestGroup.Action -> getAllChildren()
    is RequestGroup.Action.Condition -> getAllChildren()
    is RequestGroup.Action.RelatedAction -> getAllChildren()
    is MessageHeader.Destination -> getAllChildren()
    is MessageHeader.Source -> getAllChildren()
    is MessageHeader.Response -> getAllChildren()
    is DeviceDefinition.UdiDeviceIdentifier -> getAllChildren()
    is DeviceDefinition.DeviceName -> getAllChildren()
    is DeviceDefinition.Specialization -> getAllChildren()
    is DeviceDefinition.Capability -> getAllChildren()
    is DeviceDefinition.Property -> getAllChildren()
    is DeviceDefinition.Material -> getAllChildren()
    is Goal.Target -> getAllChildren()
    is ObservationDefinition.QuantitativeDetails -> getAllChildren()
    is ObservationDefinition.QualifiedInterval -> getAllChildren()
    is Immunization.Performer -> getAllChildren()
    is Immunization.Education -> getAllChildren()
    is Immunization.Reaction -> getAllChildren()
    is Immunization.ProtocolApplied -> getAllChildren()
    is ValueSet.Compose -> getAllChildren()
    is ValueSet.Compose.Include -> getAllChildren()
    is ValueSet.Compose.Include.Concept -> getAllChildren()
    is ValueSet.Compose.Include.Concept.Designation -> getAllChildren()
    is ValueSet.Compose.Include.Filter -> getAllChildren()
    is ValueSet.Expansion -> getAllChildren()
    is ValueSet.Expansion.Parameter -> getAllChildren()
    is ValueSet.Expansion.Contains -> getAllChildren()
    is ClaimResponse.Item -> getAllChildren()
    is ClaimResponse.Item.Adjudication -> getAllChildren()
    is ClaimResponse.Item.Detail -> getAllChildren()
    is ClaimResponse.Item.Detail.SubDetail -> getAllChildren()
    is ClaimResponse.AddItem -> getAllChildren()
    is ClaimResponse.AddItem.Detail -> getAllChildren()
    is ClaimResponse.AddItem.Detail.SubDetail -> getAllChildren()
    is ClaimResponse.Total -> getAllChildren()
    is ClaimResponse.Payment -> getAllChildren()
    is ClaimResponse.ProcessNote -> getAllChildren()
    is ClaimResponse.Insurance -> getAllChildren()
    is ClaimResponse.Error -> getAllChildren()
    is Contract.ContentDefinition -> getAllChildren()
    is Contract.Term -> getAllChildren()
    is Contract.Term.SecurityLabel -> getAllChildren()
    is Contract.Term.Offer -> getAllChildren()
    is Contract.Term.Offer.Party -> getAllChildren()
    is Contract.Term.Offer.Answer -> getAllChildren()
    is Contract.Term.Asset -> getAllChildren()
    is Contract.Term.Asset.Context -> getAllChildren()
    is Contract.Term.Asset.ValuedItem -> getAllChildren()
    else -> emptyList()
  }

private fun BackboneElement.getAllChildren2(): CollectionsList<Any> =
  when (this) {
    is Contract.Term.Action -> getAllChildren()
    is Contract.Term.Action.Subject -> getAllChildren()
    is Contract.Signer -> getAllChildren()
    is Contract.Friendly -> getAllChildren()
    is Contract.Legal -> getAllChildren()
    is Contract.Rule -> getAllChildren()
    is BiologicallyDerivedProduct.Collection -> getAllChildren()
    is BiologicallyDerivedProduct.Processing -> getAllChildren()
    is BiologicallyDerivedProduct.Manipulation -> getAllChildren()
    is BiologicallyDerivedProduct.Storage -> getAllChildren()
    is TerminologyCapabilities.Software -> getAllChildren()
    is TerminologyCapabilities.Implementation -> getAllChildren()
    is TerminologyCapabilities.CodeSystem -> getAllChildren()
    is TerminologyCapabilities.CodeSystem.Version -> getAllChildren()
    is TerminologyCapabilities.CodeSystem.Version.Filter -> getAllChildren()
    is TerminologyCapabilities.Expansion -> getAllChildren()
    is TerminologyCapabilities.Expansion.Parameter -> getAllChildren()
    is TerminologyCapabilities.ValidateCode -> getAllChildren()
    is TerminologyCapabilities.Translation -> getAllChildren()
    is TerminologyCapabilities.Closure -> getAllChildren()
    is ClinicalUseDefinition.Contraindication -> getAllChildren()
    is ClinicalUseDefinition.Contraindication.OtherTherapy -> getAllChildren()
    is ClinicalUseDefinition.Indication -> getAllChildren()
    is ClinicalUseDefinition.Interaction -> getAllChildren()
    is ClinicalUseDefinition.Interaction.Interactant -> getAllChildren()
    is ClinicalUseDefinition.UndesirableEffect -> getAllChildren()
    is ClinicalUseDefinition.Warning -> getAllChildren()
    is SpecimenDefinition.TypeTested -> getAllChildren()
    is SpecimenDefinition.TypeTested.Container -> getAllChildren()
    is SpecimenDefinition.TypeTested.Container.Additive -> getAllChildren()
    is SpecimenDefinition.TypeTested.Handling -> getAllChildren()
    is ConceptMap.Group -> getAllChildren()
    is ConceptMap.Group.Element -> getAllChildren()
    is ConceptMap.Group.Element.Target -> getAllChildren()
    is ConceptMap.Group.Element.Target.DependsOn -> getAllChildren()
    is ConceptMap.Group.Unmapped -> getAllChildren()
    is Invoice.Participant -> getAllChildren()
    is Invoice.LineItem -> getAllChildren()
    is Invoice.LineItem.PriceComponent -> getAllChildren()
    is StructureDefinition.Mapping -> getAllChildren()
    is StructureDefinition.Context -> getAllChildren()
    is StructureDefinition.Snapshot -> getAllChildren()
    is StructureDefinition.Differential -> getAllChildren()
    is CommunicationRequest.Payload -> getAllChildren()
    is DetectedIssue.Evidence -> getAllChildren()
    is DetectedIssue.Mitigation -> getAllChildren()
    is EvidenceVariable.Characteristic -> getAllChildren()
    is EvidenceVariable.Characteristic.TimeFromStart -> getAllChildren()
    is EvidenceVariable.Category -> getAllChildren()
    is Bundle.Link -> getAllChildren()
    is Bundle.Entry -> getAllChildren()
    is Bundle.Entry.Search -> getAllChildren()
    is Bundle.Entry.Request -> getAllChildren()
    is Bundle.Entry.Response -> getAllChildren()
    is MessageDefinition.Focus -> getAllChildren()
    is MessageDefinition.AllowedResponse -> getAllChildren()
    is ImplementationGuide.DependsOn -> getAllChildren()
    is ImplementationGuide.Global -> getAllChildren()
    is ImplementationGuide.Definition -> getAllChildren()
    is ImplementationGuide.Definition.Grouping -> getAllChildren()
    is ImplementationGuide.Definition.Resource -> getAllChildren()
    is ImplementationGuide.Definition.Page -> getAllChildren()
    is ImplementationGuide.Definition.Parameter -> getAllChildren()
    is ImplementationGuide.Definition.Template -> getAllChildren()
    is ImplementationGuide.Manifest -> getAllChildren()
    is ImplementationGuide.Manifest.Resource -> getAllChildren()
    is ImplementationGuide.Manifest.Page -> getAllChildren()
    is NutritionOrder.OralDiet -> getAllChildren()
    is NutritionOrder.OralDiet.Nutrient -> getAllChildren()
    is NutritionOrder.OralDiet.Texture -> getAllChildren()
    is NutritionOrder.Supplement -> getAllChildren()
    is NutritionOrder.EnteralFormula -> getAllChildren()
    is NutritionOrder.EnteralFormula.Administration -> getAllChildren()
    is CoverageEligibilityRequest.SupportingInfo -> getAllChildren()
    is CoverageEligibilityRequest.Insurance -> getAllChildren()
    is CoverageEligibilityRequest.Item -> getAllChildren()
    is CoverageEligibilityRequest.Item.Diagnosis -> getAllChildren()
    is CodeSystem.Filter -> getAllChildren()
    is CodeSystem.Property -> getAllChildren()
    is CodeSystem.Concept -> getAllChildren()
    is CodeSystem.Concept.Designation -> getAllChildren()
    is CodeSystem.Concept.Property -> getAllChildren()
    is MedicationRequest.DispenseRequest -> getAllChildren()
    is MedicationRequest.DispenseRequest.InitialFill -> getAllChildren()
    is MedicationRequest.Substitution -> getAllChildren()
    is ImmunizationRecommendation.Recommendation -> getAllChildren()
    is ImmunizationRecommendation.Recommendation.DateCriterion -> getAllChildren()
    is CompartmentDefinition.Resource -> getAllChildren()
    is Coverage.Class -> getAllChildren()
    is Coverage.CostToBeneficiary -> getAllChildren()
    is Coverage.CostToBeneficiary.Exception -> getAllChildren()
    is PaymentReconciliation.Detail -> getAllChildren()
    is PaymentReconciliation.ProcessNote -> getAllChildren()
    is MedicationKnowledge.RelatedMedicationKnowledge -> getAllChildren()
    is MedicationKnowledge.Monograph -> getAllChildren()
    is MedicationKnowledge.Ingredient -> getAllChildren()
    is MedicationKnowledge.Cost -> getAllChildren()
    is MedicationKnowledge.MonitoringProgram -> getAllChildren()
    is MedicationKnowledge.AdministrationGuidelines -> getAllChildren()
    is MedicationKnowledge.AdministrationGuidelines.Dosage -> getAllChildren()
    is MedicationKnowledge.AdministrationGuidelines.PatientCharacteristics -> getAllChildren()
    is MedicationKnowledge.MedicineClassification -> getAllChildren()
    is MedicationKnowledge.Packaging -> getAllChildren()
    is MedicationKnowledge.DrugCharacteristic -> getAllChildren()
    is MedicationKnowledge.Regulatory -> getAllChildren()
    is MedicationKnowledge.Regulatory.Substitution -> getAllChildren()
    is MedicationKnowledge.Regulatory.Schedule -> getAllChildren()
    is MedicationKnowledge.Regulatory.MaxDispense -> getAllChildren()
    is MedicationKnowledge.Kinetics -> getAllChildren()
    is SearchParameter.Component -> getAllChildren()
    is Person.Link -> getAllChildren()
    is AdministrableProductDefinition.Property -> getAllChildren()
    is AdministrableProductDefinition.RouteOfAdministration -> getAllChildren()
    is AdministrableProductDefinition.RouteOfAdministration.TargetSpecies -> getAllChildren()
    is AdministrableProductDefinition.RouteOfAdministration.TargetSpecies.WithdrawalPeriod ->
      getAllChildren()
    is AllergyIntolerance.Reaction -> getAllChildren()
    is PlanDefinition.Goal -> getAllChildren()
    is PlanDefinition.Goal.Target -> getAllChildren()
    is PlanDefinition.Action -> getAllChildren()
    is PlanDefinition.Action.Condition -> getAllChildren()
    is PlanDefinition.Action.RelatedAction -> getAllChildren()
    is PlanDefinition.Action.Participant -> getAllChildren()
    is PlanDefinition.Action.DynamicValue -> getAllChildren()
    is ClinicalImpression.Investigation -> getAllChildren()
    is ClinicalImpression.Finding -> getAllChildren()
    is Subscription.Channel -> getAllChildren()
    is CareTeam.Participant -> getAllChildren()
    is Device.UdiCarrier -> getAllChildren()
    is Device.DeviceName -> getAllChildren()
    is Device.Specialization -> getAllChildren()
    is Device.Version -> getAllChildren()
    is Device.Property -> getAllChildren()
    is NutritionProduct.Nutrient -> getAllChildren()
    is NutritionProduct.Ingredient -> getAllChildren()
    is NutritionProduct.ProductCharacteristic -> getAllChildren()
    is NutritionProduct.Instance -> getAllChildren()
    is Consent.Policy -> getAllChildren()
    is Consent.Verification -> getAllChildren()
    is Consent.Provision -> getAllChildren()
    is Consent.Provision.Actor -> getAllChildren()
    is Consent.Provision.Data -> getAllChildren()
    is MedicinalProductDefinition.Contact -> getAllChildren()
    is MedicinalProductDefinition.Name -> getAllChildren()
    is MedicinalProductDefinition.Name.NamePart -> getAllChildren()
    is MedicinalProductDefinition.Name.CountryLanguage -> getAllChildren()
    is MedicinalProductDefinition.CrossReference -> getAllChildren()
    is MedicinalProductDefinition.Operation -> getAllChildren()
    is MedicinalProductDefinition.Characteristic -> getAllChildren()
    is Communication.Payload -> getAllChildren()
    is StructureMap.Structure -> getAllChildren()
    else -> emptyList()
  }

private fun BackboneElement.getAllChildren3(): CollectionsList<Any> =
  when (this) {
    is StructureMap.Group -> getAllChildren()
    is StructureMap.Group.Input -> getAllChildren()
    is StructureMap.Group.Rule -> getAllChildren()
    is StructureMap.Group.Rule.Source -> getAllChildren()
    is StructureMap.Group.Rule.Target -> getAllChildren()
    is StructureMap.Group.Rule.Target.Parameter -> getAllChildren()
    is StructureMap.Group.Rule.Dependent -> getAllChildren()
    is Task.Restriction -> getAllChildren()
    is Task.Input -> getAllChildren()
    is Task.Output -> getAllChildren()
    is EvidenceReport.Subject -> getAllChildren()
    is EvidenceReport.Subject.Characteristic -> getAllChildren()
    is EvidenceReport.RelatesTo -> getAllChildren()
    is EvidenceReport.Section -> getAllChildren()
    is Practitioner.Qualification -> getAllChildren()
    is Ingredient.Manufacturer -> getAllChildren()
    is Ingredient.Substance -> getAllChildren()
    is Ingredient.Substance.Strength -> getAllChildren()
    is Ingredient.Substance.Strength.ReferenceStrength -> getAllChildren()
    is Observation.ReferenceRange -> getAllChildren()
    is Observation.Component -> getAllChildren()
    is DocumentReference.RelatesTo -> getAllChildren()
    is DocumentReference.Content -> getAllChildren()
    is DocumentReference.Context -> getAllChildren()
    is OperationOutcome.Issue -> getAllChildren()
    is MedicationDispense.Performer -> getAllChildren()
    is MedicationDispense.Substitution -> getAllChildren()
    is Account.Coverage -> getAllChildren()
    is Account.Guarantor -> getAllChildren()
    is Procedure.Performer -> getAllChildren()
    is Procedure.FocalDevice -> getAllChildren()
    is AdverseEvent.SuspectEntity -> getAllChildren()
    is AdverseEvent.SuspectEntity.Causality -> getAllChildren()
    else -> emptyList()
  }

internal fun BackboneElement.getAllChildren(): CollectionsList<Any> {
  getAllChildren0().let { if (it.isNotEmpty()) return it }
  getAllChildren1().let { if (it.isNotEmpty()) return it }
  getAllChildren2().let { if (it.isNotEmpty()) return it }
  getAllChildren3().let { if (it.isNotEmpty()) return it }
  return emptyList()
}
